= Istio and Knative Tutorial Pipelines 

The https://tekton.dev[Tekton Pipelines] that can be used to deploy:

*  https://bit.ly/istio-tutorial[Istio Tutorial] applications to OpenShift/Kubernetes
*  https://bit.ly/knative-tutorial[Knative Tutorial] applications to OpenShift/Kubernetes**(WIP)**

== Pre-req

An OpenShift4 cluster with following components:

- Istio - To play with servicemesh functionalities
- Knative Serving - To play with severless functionalities 
- https://github.com/openshift/pipelines-tutorial#install-openshift-pipelines[Install Tekton Pipelines]
- https://github.com/tektoncd/cli/releases/latest[Tekton CLI]


== Create Tutorial Project in OpenShift

[source,bash]
----
oc new-project tutorial && \
oc create serviceaccount pipeline && \
oc adm policy add-scc-to-user privileged -z pipeline && \
oc adm policy add-role-to-user edit -z pipeline && \
oc adm policy add-scc-to-user privileged -z default && \
oc adm policy add-scc-to-user anyuid -z default && \
oc create -f https://raw.githubusercontent.com/redhat-developer-demos/pipelines-catalog/master/knative-client/pipeline-sa-roles.yaml -n tutorial && \
oc policy add-role-to-user pipeline-roles -z pipeline --role-namespace=tutorial
----

== Deploy Nexus

To make maven builds faster, we will deploy Sonatype Nexus

[source,bash]
----
oc new-app sonatype/nexus
----

== Tasks

Create the following Tekton tasks which will be used in the `Pipelines`

[source,bash]
----
oc create -f https://raw.githubusercontent.com/tektoncd/catalog/master/openshift-client/openshift-client-task.yaml \
  -f https://raw.githubusercontent.com/redhat-developer-demos/pipelines-catalog/master/quarkus/s2i-quarkus-task.yaml \
  -f https://raw.githubusercontent.com/redhat-developer-demos/pipelines-catalog/master/quarkus/quarkus-native-task.yaml \
  -f https://raw.githubusercontent.com/redhat-developer-demos/pipelines-catalog/master/quarkus/quarkus-jvm-task.yaml \
  -f https://raw.githubusercontent.com/redhat-developer-demos/pipelines-catalog/master/knative-client/kn-service-create-task.yaml
----

Check the tasks created

[source,bash]
----
tkn task ls
----

```
NAME                AGE
kn-create-service   12 seconds ago
openshift-client    13 seconds ago
quarkus-jvm         12 seconds ago
quarkus-native      12 seconds ago
s2i-quarkus         13 seconds ago
```

== Application Deployment

== Download the sources

[source,bash]
----
git clone https://github.com/redhat-developer-demos/tutorials-pipelines
cd tutorials-pipelines
----

== Common

[source,bash]
----
oc create -f pipelines-common/resources.yaml \
  -f pipelines-common/pipeline-deploy.yaml \ #<1>
  -f pipelines-common/pipeline-kn-deploy.yaml #<2>
----

<1> Pipeline used for vanilla Kubernetes/OpenShift deployment
<2> Pipeline used for serverless (knative) deployment

== Customer

[source,bash]
----
oc create -f customer/app.yaml
oc create -f customer/pipeline-run.yaml
----

Watch the logs of pipeline run using the command 
[source,bash]
----
# get the running pipeline id 
tkn pipelinerun ls
# get logs of the pipeline via
tkn pipelinerun logs -a -f <id-from-previous-command>
----

== Preference

[source,bash]
----
oc create -f preference/app.yaml \
   -f preference/pipeline-run.yaml
----

Watch the logs of pipeline run using the command 

[source,bash]
----
# get the running pipeline id 
tkn pipelinerun ls
# get logs of the pipeline via
tkn pipelinerun logs -a -f <id-from-previous-command>
----


== Recommendation

=== Version 1

==== Vanilla OpenShift/Kubernetes Deployment

[source,bash]
----
oc create -f recommendation/app-v1.yaml \
  -f recommendation/pipeline-run.yaml
----

==== Knative Service Deployment

[source,bash]
----
oc create -f recommendation/kn-pipeline-run.yaml
----

Watch the logs of pipeline run using the command 

[source,bash]
----
# get the running pipeline id 
tkn pipelinerun ls
# get logs of the pipeline via
tkn pipelinerun logs -a -f <id-from-previous-command>
----

=== Version 2

==== Vanilla OpenShift/Kubernetes Deployment

[source,bash]
----
oc create -f recommendation/app-v2.yaml \
  -f recommendation/pipeline-run-v2.yaml
----

==== Knative Service Deployment

[source,bash]
----
oc create -f recommendation/kn-pipeline-v2-run.yaml
----

Watch the logs of pipeline run using the command 

[source,bash]
----
# get the running pipeline id 
tkn pipelinerun ls
# get logs of the pipeline via
tkn pipelinerun logs -a -f <id-from-previous-command>
----

=== Knative 

[source,bash]
----
oc create -f greeter/pipeline-deploy.yaml \
  -f greeter/pipeline-run.yaml
----

Watch the logs of pipeline run using the command 

[source,bash]
----
# get the running pipeline id 
tkn pipelinerun ls
# get logs of the pipeline via
tkn pipelinerun logs -a -f <id-from-previous-command>
----

== Cleanup

* Delete all pipeline runs 
[source,bash]
----
tkn pipelinerun ls | awk 'NR>1{print $1}' | xargs oc delete pipelinerun 
----

* Delete all pipelines
[source,bash]
----
oc delete -f pipelines-commons/pipeline-deploy.yaml
----

* Delete applications
[source,bash]
----
oc delete -f recommendation/app-v1.yaml \
  -f recommendation/app-v2.yaml \
  -f preference/app.yaml \
  -f customer/app.yaml 
----
