= Istio and Knative Tutorial Pipelines 

The https://tekton.dev[Tekton Pipelines] that can be used to deploy:

*  https://bit.ly/istio-tutorial[Istio Tutorial] applications to OpenShift/Kubernetes
*  https://bit.ly/knative-tutorial[Knative Tutorial] applications to OpenShift/Kubernetes**(WIP)**

== Pre-req

An OpenShift4 cluster with following components:

- Istio - To play with servicemesh functionalities
- Knative Serving - To play with severless functionalities 
- https://github.com/openshift/pipelines-tutorial#install-openshift-pipelines[Install Tekton Pipelines]
- https://github.com/tektoncd/cli/releases/latest[Tekton CLI]


== Create Tutorial Project in OpenShift

[source,bash]
----
oc new-project tutorial && \
oc create serviceaccount pipeline && \
oc adm policy add-scc-to-user privileged -z pipeline && \
oc adm policy add-role-to-user edit -z pipeline && \
oc adm policy add-scc-to-user privileged -z default && \
oc adm policy add-scc-to-user anyuid -z default
----

== Deploy Nexus

To make maven builds faster, we will deploy Sonatype Nexus

[source,bash]
----
oc new-app sonatype/nexus && \
oc expose svc/nexus
----

== Tasks

Create the following Tekton tasks which will be used in the `Pipelines`

[source,bash]
----
oc create -f https://raw.githubusercontent.com/tektoncd/catalog/master/openshift-client/openshift-client-task.yaml && \
oc create -f https://raw.githubusercontent.com/openshift/pipelines-catalog/master/s2i-java-8/s2i-java-8-task.yaml && \
oc create -f https://raw.githubusercontent.com/redhat-developer-demos/pipelines-catalog/master/quarkus/s2i-quarkus-task.yaml
----

== Application Deployment

== Common

[source,bash]
----
oc create -f pipelines-common/resources.yaml
----

== Customer

[source,bash]
----
oc create -f customer/app.yaml && \
oc create -f customer/pipeline-deploy.yaml && \
oc create -f customer/pipeline-run.yaml
----

Watch the logs of pipeline run using the command 
[source,bash]
----
# get the running pipeline id 
tkn pipelinerun ls
# get logs of the pipeline via
tkn pipelinerun logs -a -f <id-from-previous-command>
----

== Preference

[source,bash]
----
oc create -f preference/app.yaml && \
oc create -f preference/pipeline-deploy.yaml && \
oc create -f preference/pipeline-run.yaml
----

Watch the logs of pipeline run using the command 

[source,bash]
----
# get the running pipeline id 
tkn pipelinerun ls
# get logs of the pipeline via
tkn pipelinerun logs -a -f <id-from-previous-command>
----


== Recommendation

=== Version 1

[source,bash]
----
oc create -f recommendation/deployment-v1.yaml && \
oc create -f recommendation/pipeline-deploy.yaml && \
oc create -f recommendation/pipeline-run.yaml
----

Watch the logs of pipeline run using the command 

[source,bash]
----
# get the running pipeline id 
tkn pipelinerun ls
# get logs of the pipeline via
tkn pipelinerun logs -a -f <id-from-previous-command>
----

=== Version 2

[source,bash]
----
oc create -f recommendation/deployment-v2.yaml && \
oc create -f recommendation/pipeline-run-v2.yaml
----

Watch the logs of pipeline run using the command 

[source,bash]
----
# get the running pipeline id 
tkn pipelinerun ls
# get logs of the pipeline via
tkn pipelinerun logs -a -f <id-from-previous-command>
----

== Cleanup

* Delete all pipeline runs 
[source,bash]
----
tkn pipelinerun ls | awk 'NR>1{print $1}' | xargs oc delete pipelinerun 
----

* Delete all pipelines
[source,bash]
----
oc delete -f recommendation/pipeline-deploy.yaml && \
   -f preference/pipeline-deploy.yaml && \
   -f customer/pipeline-deploy.yaml 
----

* Delete applications
[source,bash]
----
oc delete -f recommendation/deployment-v1.yaml && \
  -f recommendation/deployment-v2.yaml && \
  -f preference/app.yaml && \
  -f customer/app.yaml 
----
