FROM registry.fedoraproject.org/fedora-minimal
WORKDIR /work/
COPY target/*-runner /work/greeter
RUN chmod 775 /work
EXPOSE 8080
CMD ["./greeter", "-Dquarkus.http.host=0.0.0.0","-Xmx8m", "-Xmn8m", "-Xms8m"]
